# This is a workflow to run python script for on-boarding to Checkmarx

name: CHECKMARX_ONBOARD

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule
  workflow_dispatch:
  # Run script at 12PM everyday
  schedule:
    - cron: "0 12 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-script"
  create-CX-groups:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout git code to run these workflows
      - name: Check out repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Configure git to set up the repo
      - name: configure git
        run: |
          git checkout main
          git fetch origin
      # Set up python to run the script
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      # Runs the script stored in .github/script
      - name: Run script
        env:
          CX_CLIENT_ID: ${{ vars.CX_CLIENT_ID }}
          CX_TENANT_NAME: ${{ vars.CX_TENANT_NAME }}
          CX_TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL }}
          CX_TENANT_URL: ${{ vars.CX_TENANT_URL }}
          CX_TOKEN: ${{ secrets.CX_TOKEN }}
        run: python3 .github/scripts/checkmarx_group_onboard.py
